아래 문제들은 결과 출력까시 실행 후 노트북 파일을 제출

1.1차원이면서 크기가 10이고 0으로 채워진 배열을 생성하고 다섯번째 요소를 1로 설정하는 코드를 작성하시오. 

In [ ]:
import numpy as np
a = np.zeros(10, dtype = int)
a[4:5] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

2.아래와 같은 배열을 생성하는 code를 작성하시오.
arange 사용

[3,6,9,12,15,18,21]

In [39]:
import numpy as np
a = np.arange(3, 22, 3)
a

array([ 3,  6,  9, 12, 15, 18, 21])

3.0부터 8까지의 값을 가지고 크기가 3x3인 행렬을 arange와 reshape 명령어를 이용하여 생성 하시오. 

[[0 1 2]    
 [3,4,5]  
 [6,7,8]]


In [38]:
import numpy as np
a = np.arange(0, 9, 1)
a.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4.난수로 채워진 3x3 배열을 생성하고 최대값과 최소값을 구하는 코드를 작성 하시오

In [37]:
import numpy as np
a = np.random.rand(3, 3)
np.max(a), np.min(a)

(0.8022837358864521, 0.12196426367125623)

5.다음과 같은 행렬을 만드는 code를 작성하시오. 
(ones 함수와 slicing 이용)

[[1,1,1,0,0]    
  [1,1,1,0,0]  
  [1,1,1,0,0]   
  [1,1,1,1,1]] 

In [36]:
import numpy as np
a = np.ones((4, 5), dtype = int)
a[:3, 3:5] = 0
a

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1]])

6.5x5 행렬을 만들어 체스보드 패턴으로 채워보자
( zeros 함수와 slicing 이용)

[[0,1,0,1,0]  
[1,0,1,0,1]  
[0,1,0,1,0]  
[1,0,1,0,1]  
[0,1,0,1,0]]  

In [35]:
import numpy as np
a = np. zeros((5,5), dtype = int)
a[::2, 1::2] = 1
a[1::2, ::2] = 1
a

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])